alert_pipelines:
  - alert_name: NOOP_ALERT
    enrichments:
      - enrichment_name: NOOP_ENRICHMENT
        enrichment_args: ARG1,ARG2
    actions:
      - action_name: NOOP_ACTION
        action_args: ARG1,ARG2
  - alert_name: KubePodCrashLooping
    enrichments:
      - enrichment_name: GetMetric
        enrichment_args: "promql"
    actions:
      - action_name: NotifySLack
        action_args: "url"
