version: "3.5"
services:
  toy_alert_manager:
    container_name: toy_alert_manager
    image: alertmanager:0.0.1
    restart: always
    network_mode: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./alert-manager-config.yml:/alert-manager-config.yml
    command:
      - server
      - --config-file
      - "./alert-manager-config.yml"
      - --log-level
      - DEBUG
